#!/bin/bash

# Copyright 2016 AGH Strategies, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function switchsite() {
  base=`pwd -P`
  if [[ $1 && ( ${base:0:9} == '/srv/www/' ) ]]
    then
      # without /srv/www/:
      shortbase=${base:9}
      slashpos=`expr index $shortbase /`
      newdir="/srv/www/$1/${shortbase:$slashpos}"
      cd $newdir
    else
      echo 'An argument is required and you must be within /srv/www/

Usage:
  switchsite dirname

This will move you to /srv/www/dirname/path if you are currently at
/srv/www/currentdir/path'
  fi
}
